export const PRINTER_PRESETS = [
  { id: 'custom', name: 'Otro / Personalizado', defaultWatts: 120 },
  { id: 'ender-3-v3-se', name: 'Creality Ender 3 V3 SE', defaultWatts: 120 },
  { id: 'ender-3-v3-ke', name: 'Creality Ender 3 V3 KE', defaultWatts: 140 },
  { id: 'ender-3-v2', name: 'Creality Ender 3 V2 / Pro', defaultWatts: 110 },
  { id: 'creality-k1', name: 'Creality K1 / K1C', defaultWatts: 200 },
  { id: 'creality-k1-max', name: 'Creality K1 Max', defaultWatts: 280 },
  { id: 'bambu-a1-mini', name: 'Bambu Lab A1 Mini', defaultWatts: 90 },
  { id: 'bambu-a1', name: 'Bambu Lab A1', defaultWatts: 130 },
  { id: 'bambu-p1s', name: 'Bambu Lab P1S / P1P', defaultWatts: 160 },
  { id: 'bambu-x1c', name: 'Bambu Lab X1-Carbon', defaultWatts: 180 },
  { id: 'artillery-genius', name: 'Artillery Genius / Pro', defaultWatts: 120 },
  { id: 'artillery-sidewinder', name: 'Artillery Sidewinder X2/X3', defaultWatts: 180 },
  { id: 'prusa-mk4', name: 'Original Prusa MK4', defaultWatts: 120 },
  { id: 'prusa-mini', name: 'Original Prusa MINI+', defaultWatts: 85 },
  { id: 'kingroon-kp3s', name: 'Kingroon KP3S Pro', defaultWatts: 100 },
  { id: 'anycubic-kobra-2', name: 'Anycubic Kobra 2 Series', defaultWatts: 130 },
  { id: 'elegoo-neptune-4', name: 'Elegoo Neptune 4 / Pro', defaultWatts: 150 },
  { id: 'resina-lcd', name: 'Impresora Resina LCD (~6-8K)', defaultWatts: 55 },
];
